services:

  backend:
    image: ghcr.io/pdiegmann/opet/backend:latest
    restart: unless-stopped
    container_name: backend
    volumes:
      - opet_data:/var/lib/opet
    env_file:
      - .env
    environment:
      DATABASE_URL: file:/var/lib/opet/opet.db
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"

  frontend:
    image: ghcr.io/pdiegmann/opet/frontend:latest
    restart: unless-stopped
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  opet_data: